name: recreshow_system
description: "Recreashow System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  injectable: ^2.3.2
  get_it: ^7.6.7
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  go_router: ^8.2.0
  equatable: ^2.0.5
  geolocator: ^11.0.0
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  shimmer: ^3.0.0
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.3
  path: ^1.9.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/